import { KMSClient, GenerateDataKeyCommand, DecryptCommand } from '@aws-sdk/client-kms';
import * as crypto from 'crypto';
import { logger } from '../utils/logger';

/**
 * KMS Envelope Encryption Service
 * 
 * Implements envelope encryption pattern:
 * 1. Generate a Data Encryption Key (DEK) via AWS KMS
 * 2. KMS returns both plaintext DEK and KMS-encrypted DEK
 * 3. Use plaintext DEK to encrypt relayer private keys (AES-256-GCM)
 * 4. Store only the KMS-encrypted DEK in database (never plaintext DEK)
 * 5. To decrypt: ask KMS to decrypt the encrypted DEK, use result to decrypt private key
 * 
 * Security benefits:
 * - Private keys are encrypted with unique DEKs (not a shared master key)
 * - DEKs are protected by AWS KMS HSM
 * - DEK rotation doesn't require re-keying KMS
 * - Audit trail via CloudTrail for all KMS operations
 */

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12;
const TAG_LENGTH = 16;
const DEK_LENGTH = 32; // 256 bits

export interface EncryptedData {
  ciphertext: string; // Hex-encoded: iv + encrypted data + auth tag
  encryptedDek: string; // Base64-encoded KMS-encrypted DEK
  dekVersion: number;
}

export interface DecryptedDek {
  plaintextDek: Buffer;
  encryptedDek: string;
}

/**
 * Custom error for KMS envelope encryption operations
 */
export class KmsEnvelopeError extends Error {
  constructor(
    message: string,
    public readonly code: string,
    public readonly cause?: any,
  ) {
    super(message);
    this.name = 'KmsEnvelopeError';
  }
}

/**
 * KmsEnvelopeService — Manages envelope encryption using AWS KMS
 * 
 * This service NEVER stores plaintext DEKs. All DEKs are:
 * 1. Generated by KMS
 * 2. Used immediately for encryption
 * 3. Zero-wiped from memory after use
 * 4. Stored only in KMS-encrypted form
 */
export class KmsEnvelopeService {
  private readonly kmsClient: KMSClient;
  private readonly kmsKeyId: string;

  constructor(kmsKeyId?: string, kmsClient?: KMSClient) {
    this.kmsKeyId = kmsKeyId || process.env.KMS_ENVELOPE_KEY_ID || '';
    
    if (!this.kmsKeyId) {
      throw new KmsEnvelopeError(
        'KMS_ENVELOPE_KEY_ID environment variable is required',
        'MISSING_KMS_KEY_ID',
      );
    }

    this.kmsClient = kmsClient || new KMSClient({ 
      region: process.env.AWS_REGION || 'us-east-1' 
    });

    logger.info(`[KmsEnvelopeService] Initialized with KMS key: ${this.maskKeyId(this.kmsKeyId)}`);
  }

  /**
   * Generates a new Data Encryption Key (DEK) via AWS KMS.
   * 
   * @returns Object containing plaintext DEK (for immediate use) and encrypted DEK (for storage)
   * @throws KmsEnvelopeError if KMS operation fails
   */
  async generateDataKey(): Promise<DecryptedDek> {
    try {
      logger.info('[KmsEnvelopeService] Generating new DEK via KMS...');

      const command = new GenerateDataKeyCommand({
        KeyId: this.kmsKeyId,
        KeySpec: 'AES_256', // Generate 256-bit key
      });

      const response = await this.kmsClient.send(command);

      if (!response.Plaintext || !response.CiphertextBlob) {
        throw new Error('KMS returned incomplete data key');
      }

      // Convert KMS response to buffers
      const plaintextDek = Buffer.from(response.Plaintext);
      const encryptedDekBuffer = Buffer.from(response.CiphertextBlob);

      if (plaintextDek.length !== DEK_LENGTH) {
        throw new Error(`Expected ${DEK_LENGTH}-byte DEK, got ${plaintextDek.length} bytes`);
      }

      logger.info('[KmsEnvelopeService] DEK generated successfully');

      return {
        plaintextDek,
        encryptedDek: encryptedDekBuffer.toString('base64'),
      };
    } catch (error: any) {
      logger.error('[KmsEnvelopeService] Failed to generate DEK:', error);
      throw new KmsEnvelopeError(
        `Failed to generate data key: ${error.message}`,
        'DEK_GENERATION_FAILED',
        error,
      );
    }
  }

  /**
   * Decrypts a KMS-encrypted DEK to get the plaintext key.
   * 
   * @param encryptedDek - Base64-encoded KMS-encrypted DEK
   * @returns Plaintext DEK as Buffer (caller must zero-wipe after use)
   * @throws KmsEnvelopeError if decryption fails
   */
  async decryptDataKey(encryptedDek: string): Promise<Buffer> {
    try {
      logger.info('[KmsEnvelopeService] Decrypting DEK via KMS...');

      const command = new DecryptCommand({
        KeyId: this.kmsKeyId,
        CiphertextBlob: Buffer.from(encryptedDek, 'base64'),
      });

      const response = await this.kmsClient.send(command);

      if (!response.Plaintext) {
        throw new Error('KMS returned empty plaintext');
      }

      const plaintextDek = Buffer.from(response.Plaintext);

      if (plaintextDek.length !== DEK_LENGTH) {
        throw new Error(`Expected ${DEK_LENGTH}-byte DEK, got ${plaintextDek.length} bytes`);
      }

      logger.info('[KmsEnvelopeService] DEK decrypted successfully');

      return plaintextDek;
    } catch (error: any) {
      logger.error('[KmsEnvelopeService] Failed to decrypt DEK:', error);
      throw new KmsEnvelopeError(
        `Failed to decrypt data key: ${error.message}`,
        'DEK_DECRYPTION_FAILED',
        error,
      );
    }
  }

  /**
   * Encrypts data using a DEK with AES-256-GCM.
   * 
   * @param plaintext - Data to encrypt (e.g., Ed25519 private key)
   * @param plaintextDek - 32-byte DEK for encryption
   * @returns Hex-encoded ciphertext (format: iv + ciphertext + authTag)
   */
  private encryptWithDek(plaintext: string, plaintextDek: Buffer): string {
    if (plaintextDek.length !== DEK_LENGTH) {
      throw new KmsEnvelopeError(
        `Invalid DEK length: expected ${DEK_LENGTH} bytes, got ${plaintextDek.length}`,
        'INVALID_DEK_LENGTH',
      );
    }

    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv(ALGORITHM, plaintextDek, iv);

    let encrypted = cipher.update(plaintext, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    const tag = cipher.getAuthTag();

    // Format: iv (12 bytes) + ciphertext + authTag (16 bytes)
    return iv.toString('hex') + encrypted + tag.toString('hex');
  }

  /**
   * Decrypts data using a DEK with AES-256-GCM.
   * 
   * @param ciphertext - Hex-encoded encrypted data (format: iv + ciphertext + authTag)
   * @param plaintextDek - 32-byte DEK for decryption
   * @returns Decrypted plaintext string
   */
  private decryptWithDek(ciphertext: string, plaintextDek: Buffer): string {
    if (plaintextDek.length !== DEK_LENGTH) {
      throw new KmsEnvelopeError(
        `Invalid DEK length: expected ${DEK_LENGTH} bytes, got ${plaintextDek.length}`,
        'INVALID_DEK_LENGTH',
      );
    }

    try {
      const buffer = Buffer.from(ciphertext, 'hex');

      const iv = buffer.subarray(0, IV_LENGTH);
      const tag = buffer.subarray(buffer.length - TAG_LENGTH);
      const encryptedData = buffer.subarray(IV_LENGTH, buffer.length - TAG_LENGTH);

      const decipher = crypto.createDecipheriv(ALGORITHM, plaintextDek, iv);
      decipher.setAuthTag(tag);

      let decrypted = decipher.update(encryptedData, undefined, 'utf8');
      decrypted += decipher.final('utf8');

      return decrypted;
    } catch (err: any) {
      throw new KmsEnvelopeError(
        `Decryption failed: ${err.message}`,
        'DECRYPTION_FAILED',
        err,
      );
    }
  }

  /**
   * Encrypts data using envelope encryption.
   * 
   * Process:
   * 1. Generate new DEK via KMS
   * 2. Encrypt data with plaintext DEK
   * 3. Zero-wipe plaintext DEK
   * 4. Return ciphertext + encrypted DEK
   * 
   * @param plaintext - Data to encrypt (e.g., Ed25519 private key hex)
   * @param dekVersion - Version number for DEK rotation tracking
   * @returns Encrypted data bundle with KMS-encrypted DEK
   */
  async encrypt(plaintext: string, dekVersion: number = 1): Promise<EncryptedData> {
    let plaintextDek: Buffer | null = null;

    try {
      // Step 1: Generate DEK via KMS
      const { plaintextDek: dek, encryptedDek } = await this.generateDataKey();
      plaintextDek = dek;

      // Step 2: Encrypt data with DEK
      const ciphertext = this.encryptWithDek(plaintext, plaintextDek);

      logger.info('[KmsEnvelopeService] Data encrypted successfully');

      // Step 3: Return encrypted bundle (DEK is KMS-protected)
      return {
        ciphertext,
        encryptedDek,
        dekVersion,
      };
    } finally {
      // Step 4: Zero-wipe plaintext DEK from memory
      if (plaintextDek) {
        plaintextDek.fill(0);
      }
    }
  }

  /**
   * Decrypts data using envelope encryption.
   * 
   * Process:
   * 1. Decrypt DEK via KMS
   * 2. Use plaintext DEK to decrypt data
   * 3. Zero-wipe plaintext DEK
   * 4. Return decrypted data
   * 
   * @param encryptedData - Encrypted data bundle (ciphertext + encrypted DEK)
   * @returns Decrypted plaintext string
   */
  async decrypt(encryptedData: EncryptedData): Promise<string> {
    let plaintextDek: Buffer | null = null;

    try {
      // Step 1: Decrypt DEK via KMS
      plaintextDek = await this.decryptDataKey(encryptedData.encryptedDek);

      // Step 2: Decrypt data with plaintext DEK
      const plaintext = this.decryptWithDek(encryptedData.ciphertext, plaintextDek);

      logger.info('[KmsEnvelopeService] Data decrypted successfully');

      return plaintext;
    } finally {
      // Step 3: Zero-wipe plaintext DEK from memory
      if (plaintextDek) {
        plaintextDek.fill(0);
      }
    }
  }

  /**
   * Re-encrypts data with a new DEK (for DEK rotation).
   * 
   * Process:
   * 1. Decrypt data with old DEK
   * 2. Generate new DEK
   * 3. Encrypt data with new DEK
   * 4. Zero-wipe both DEKs
   * 5. Return new encrypted bundle
   * 
   * @param encryptedData - Current encrypted data bundle
   * @param newDekVersion - New DEK version number
   * @returns New encrypted data bundle with rotated DEK
   */
  async rotateEncryption(
    encryptedData: EncryptedData,
    newDekVersion: number,
  ): Promise<EncryptedData> {
    let oldDek: Buffer | null = null;
    let newDek: Buffer | null = null;

    try {
      logger.info(`[KmsEnvelopeService] Rotating DEK from v${encryptedData.dekVersion} to v${newDekVersion}...`);

      // Step 1: Decrypt with old DEK
      oldDek = await this.decryptDataKey(encryptedData.encryptedDek);
      const plaintext = this.decryptWithDek(encryptedData.ciphertext, oldDek);

      // Step 2: Generate new DEK
      const { plaintextDek, encryptedDek } = await this.generateDataKey();
      newDek = plaintextDek;

      // Step 3: Encrypt with new DEK
      const ciphertext = this.encryptWithDek(plaintext, newDek);

      logger.info('[KmsEnvelopeService] DEK rotation completed successfully');

      return {
        ciphertext,
        encryptedDek,
        dekVersion: newDekVersion,
      };
    } finally {
      // Step 4: Zero-wipe both DEKs
      if (oldDek) oldDek.fill(0);
      if (newDek) newDek.fill(0);
    }
  }

  /**
   * Validates that encrypted data can be successfully decrypted.
   * Useful for testing and sanity checks.
   * 
   * @param encryptedData - Encrypted data bundle to validate
   * @returns true if decryption succeeds, false otherwise
   */
  async validateEncryption(encryptedData: EncryptedData): Promise<boolean> {
    try {
      await this.decrypt(encryptedData);
      return true;
    } catch (error) {
      logger.error('[KmsEnvelopeService] Validation failed:', error);
      return false;
    }
  }

  /**
   * Masks KMS key ID for safe logging (shows last 8 chars only)
   */
  private maskKeyId(keyId: string): string {
    if (keyId.length <= 8) return '***';
    return '***' + keyId.slice(-8);
  }

  /**
   * Returns KMS client for advanced operations (use with caution)
   */
  getKmsClient(): KMSClient {
    return this.kmsClient;
  }

  /**
   * Returns the KMS key ID being used
   */
  getKeyId(): string {
    return this.kmsKeyId;
  }
}

// Singleton instance for application-wide use
let envelopeServiceInstance: KmsEnvelopeService | null = null;

/**
 * Gets or creates the singleton KmsEnvelopeService instance
 */
export function getKmsEnvelopeService(): KmsEnvelopeService {
  if (!envelopeServiceInstance) {
    envelopeServiceInstance = new KmsEnvelopeService();
  }
  return envelopeServiceInstance;
}

/**
 * Sets a custom KmsEnvelopeService instance (for testing)
 */
export function setKmsEnvelopeService(service: KmsEnvelopeService): void {
  envelopeServiceInstance = service;
}

/**
 * Resets the singleton instance (for testing)
 */
export function resetKmsEnvelopeService(): void {
  envelopeServiceInstance = null;
}
